### ISSUE TITLE
Missing Code for Generating Pickle Files

### ISSUE THREAD

**Issue by Humanity123** [ccsasuke/man#1]
Can you provide a description of the data present in the Pickle files for Multi Domain Amazon Dataset?
Or code for generating these pickle files

**Comment by ccsasuke** [comment]
We took the preprocessed version of the Amazon dataset from the mSDA paper (https://www.cse.wustl.edu/~mchen/code/mSDA.tar) that comes in a Matlab format (.mat).

I guess I further converted that into a pickle file and did some reorganization of the data, such as splitting the data into "labeled" and "unlabeled" sets, etc.
Sorry I can no longer locate the script I used for this conversion, but I can briefly describe the structure of the pkl file. The relevant code for consuming the pkl file can be found in `data_prep/msda_preprocessed_amazon_dataset.py`

The pickled file contains a single dictionary with two keys "labeled" and "unlabeled". For each of the two items, it contains a tuple (x, y), where x is a 2d numpy array containing the input while y is a 1d numpy array with the labels.
You can also modify `msda_preprocessed_amazon_dataset.py
` to use with other data formats.

**Comment by Humanity123** [comment]
Hey,

I looked at the pickle files. The matrix was of the shape (Number of data
points, 30000). I wanted to test your implementation on different Amazon
dataset. I believe that 30000 feature vector was constructed using the
unigrams and bigram features. Can you explain the process of generating the
feature vector of size 30000.

**Comment by ccsasuke** [comment]
Hi,

As I mentioned, the 30k dimensional matrix is taken from the mSDA paper by Chen et al. (2012), so I cannot speak for them about how exactly they processed the dataset. However, I believe they simply took the most frequent 30000 features (and we only use the top 5k to be consistent to some earlier work we compared as baselines).
