### ISSUE TITLE
Source of Word Vectors

### ISSUE THREAD

**Issue by Humanity123** [ccsasuke/man#2]
Experiment 3 uses pre trained word vectors of 100 dimension. It has not been mentioned in the paper or the repository the source of the embeddings. Can you please briefly explain the method used for training the embeddings?
Moreover does the choice of embeddings affect the results?

**Comment by ccsasuke** [comment]
Hi,

We actually (briefly) mentioned how the embeddings are obtained in the paper: 

> We use word2vec word embeddings
(Mikolov et al., 2013) trained on a bunch
of unlabeled raw Amazon reviews (Blitzer et al.,
2007).

We haven't experimented with alternative embedding choices, so I don't have an answer for that question at this moment.
